import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Titillium_Web } from 'next/font/google'
import "./globals.css";


const titill = Titillium_Web({ weight: ["400"], subsets: ["latin"] })

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={titill.className}>
      {children}</body>
    </html>
  );
}
